zsh ./asdf.sh
zsh ./database.sh
zsh ./git.sh
zsh ./gpg.sh
zsh ./package_management.sh
zsh ./postman.sh
zsh ./rancher.sh
zsh ./signal.sh
zsh ./slack.sh
zsh ./terminal.sh
zsh ./vscodium.sh
zsh ./whatsapp.sh
zsh ./zed.sh
